/// <mls shortName="collabLanguages" project="100554" enhancement="_100554_enhancementLit" groupName="other" />

export const languages: ICollabLanguage[] = [
    { code: 'af-ZA', name: 'Afrikaans (South Africa)' },
    { code: 'am-ET', name: 'Amharic (Ethiopia)' },
    { code: 'ar', name: 'Arabic' },
    { code: 'ar-DZ', name: 'Arabic (Algeria)' },
    { code: 'ar-BH', name: 'Arabic (Bahrain)' },
    { code: 'ar-EG', name: 'Arabic (Egypt)' },
    { code: 'ar-IQ', name: 'Arabic (Iraq)' },
    { code: 'ar-JO', name: 'Arabic (Jordan)' },
    { code: 'ar-KW', name: 'Arabic (Kuwait)' },
    { code: 'ar-LB', name: 'Arabic (Lebanon)' },
    { code: 'ar-LY', name: 'Arabic (Libya)' },
    { code: 'ar-MA', name: 'Arabic (Morocco)' },
    { code: 'ar-OM', name: 'Arabic (Oman)' },
    { code: 'ar-QA', name: 'Arabic (Qatar)' },
    { code: 'ar-SA', name: 'Arabic (Saudi Arabia)' },
    { code: 'ar-SY', name: 'Arabic (Syria)' },
    { code: 'ar-TN', name: 'Arabic (Tunisia)' },
    { code: 'ar-AE', name: 'Arabic (U.A.E.)' },
    { code: 'ar-YE', name: 'Arabic (Yemen)' },
    { code: 'hy-AM', name: 'Armenian (Armenia)' },
    { code: 'as', name: 'Assamese (India)' },
    { code: 'az-Cyrl-AZ', name: 'Azerbaijani (Cyrillic, Azerbaijan)' },
    { code: 'az-Latn-AZ', name: 'Azerbaijani (Latin, Azerbaijan)' },
    { code: 'ba-RU', name: 'Bashkir (Russia)' },
    { code: 'be-BY', name: 'Belarusian (Belarus)' },
    { code: 'bn-BD', name: 'Bengali (Bangladesh)' },
    { code: 'bn-IN', name: 'Bengali (India)' },
    { code: 'bs-Cyrl-BA', name: 'Bosnian (Cyrillic, Bosnia and Herzegovina)' },
    { code: 'bs-Latn-BA', name: 'Bosnian (Latin, Bosnia and Herzegovina)' },
    { code: 'br-FR', name: 'Breton (France)' },
    { code: 'bg-BG', name: 'Bulgarian (Bulgaria)' },
    { code: 'ca-ES', name: 'Catalan (Catalan)' },
    { code: 'chr-Cher-US', name: 'Cherokee (Cherokee)' },
    { code: 'cs', name: 'Czech' },
    { code: 'da', name: 'Danish' },
    { code: 'de', name: 'German' },
    { code: 'de-AT', name: 'German (Austria)' },
    { code: 'de-CH', name: 'German (Switzerland)' },
    { code: 'de-DE', name: 'German (Germany)' },
    { code: 'dsb', name: 'Lower Sorbian' },
    { code: 'en-AU', name: 'English (Australian)' },
    { code: 'en-CA', name: 'English (Canadian)' },
    { code: 'en-GB', name: 'English (British)' },
    { code: 'en-NZ', name: 'English (New Zealand)' },
    { code: 'en-US', name: 'English (US)' },
    { code: 'en-ZA', name: 'English (South African)' },
    { code: 'eu-ES', name: 'Basque (Basque)' },
    { code: 'el', name: 'Greek' },
    { code: 'eo', name: 'Esperanto' },
    { code: 'es', name: 'Spanish' },
    { code: 'es-AR', name: 'Spanish (Argentina)' },
    { code: 'es-CL', name: 'Spanish (Chile)' },
    { code: 'es-CO', name: 'Spanish (Colombia)' },
    { code: 'es-ES', name: 'Spanish (Spain)' },
    { code: 'es-MX', name: 'Spanish (Mexico)' },
    { code: 'et', name: 'Estonian' },
    { code: 'eu', name: 'Basque' },
    { code: 'fa', name: 'Persian' },
    { code: 'fi', name: 'Finnish' },
    { code: 'fj-FJ', name: 'Fijian' },
    { code: 'fr', name: 'French' },
    { code: 'fur-IT', name: 'Friulian' },
    { code: 'fy-NL', name: 'Frisian' },
    { code: 'ga', name: 'Irish' },
    { code: 'ga-IE', name: 'Irish (Ireland)' },
    { code: 'gd', name: 'Gaelic (Scotland)' },
    { code: 'gl', name: 'Galician' },
    { code: 'gsw-FR', name: 'Alsatian (France)' },
    { code: 'gu-IN', name: 'Gujarati' },
    { code: 'he', name: 'Hebrew' },
    { code: 'hi', name: 'Hindi' },
    { code: 'hi-IN', name: 'Hindi (India)' },
    { code: 'hr', name: 'Croatian' },
    { code: 'hsb', name: 'Upper Sorbian' },
    { code: 'hu', name: 'Hungarian' },
    { code: 'hy-AM', name: 'Armenian' },
    { code: 'id', name: 'Indonesian' },
    { code: 'is', name: 'Icelandic' },
    { code: 'it', name: 'Italian' },
    { code: 'ja', name: 'Japanese' },
    { code: 'ja-JP-mac', name: 'Japanese' },
    { code: 'ka', name: 'Georgian' },
    { code: 'kk', name: 'Kazakh' },
    { code: 'kn', name: 'Kannada' },
    { code: 'ko', name: 'Korean' },
    { code: 'ku', name: 'Kurdish' },
    { code: 'ku-Arab-IQ', name: 'Central Kurdish (Iraq)' },
    { code: 'la', name: 'Latin' },
    { code: 'lg', name: 'Luganda' },
    { code: 'lt', name: 'Lithuanian' },
    { code: 'lv', name: 'Latvian' },
    { code: 'mai', name: 'Maithili' },
    { code: 'mg', name: 'Malagasy' },
    { code: 'mi', name: 'Maori (Aotearoa)' },
    { code: 'mk', name: 'Macedonian' },
    { code: 'ml', name: 'Malayalam' },
    { code: 'mn', name: 'Mongolian' },
    { code: 'mr', name: 'Marathi' },
    { code: 'my-MM', name: 'Burmese (Myanmar)' },
    { code: 'nl', name: 'Dutch' },
    { code: 'nb-NO', name: 'Norwegian (Bokmål)' },
    { code: 'ne-NP', name: 'Nepali' },
    { code: 'nn-NO', name: 'Norwegian (Nynorsk)' },
    { code: 'nr', name: 'Ndebele, South' },
    { code: 'nso', name: 'Northern Sotho' },
    { code: 'oc', name: 'Occitan (Lengadocian)' },
    { code: 'or', name: 'Oriya' },
    { code: 'pa-IN', name: 'Punjabi' },
    { code: 'pl', name: 'Polish' },
    { code: 'pt-BR', name: 'Portuguese (Brazilian)' },
    { code: 'pt-PT', name: 'Portuguese (Portugal)' },
    { code: 'ro', name: 'Romanian' },
    { code: 'rm', name: 'Romansh' },
    { code: 'ru', name: 'Russian' },
    { code: 'rw', name: 'Kinyarwanda' },
    { code: 'si', name: 'Sinhala' },
    { code: 'sk', name: 'Slovak' },
    { code: 'sl', name: 'Slovenian' },
    { code: 'son', name: 'Songhai' },
    { code: 'sq-AL', name: 'Albanian (Albania)' },
    { code: 'sr', name: 'Serbian' },
    { code: 'sr-Latn', name: 'Serbian Latn' },
    { code: 'ss', name: 'Siswati' },
    { code: 'st', name: 'Southern Sotho' },
    { code: 'sv-SE', name: 'Swedish' },
    { code: 'ta', name: 'Tamil' },
    { code: 'ta-IN', name: 'Tamil (India)' },
    { code: 'ta-LK', name: 'Tamil (Sri Lanka)' },
    { code: 'te', name: 'Telugu' },
    { code: 'th', name: 'Thai' },
    { code: 'tn', name: 'Tswana' },
    { code: 'tr', name: 'Turkish' },
    { code: 'ts', name: 'Tsonga' },
    { code: 'tt-RU', name: 'Tatar' },
    { code: 'tzm-Latn-DZ', name: 'Central Atlas Tamazight (Latin, Algeria)' },
    { code: 'tzm-Tfng-MA', name: 'Central Atlas Tamazight (Tifinagh, Morocco)' },
    { code: 'uk', name: 'Ukrainian' },
    { code: 'ur', name: 'Urdu' },
    { code: 've', name: 'Venda' },
    { code: 'vi', name: 'Vietnamese' },
    { code: 'cy', name: 'Welsh' },
    { code: 'wo', name: 'Wolof' },
    { code: 'xh', name: 'Xhosa' },
    { code: 'zh-CN', name: 'Chinese (Simplified)' },
    { code: 'zh-TW', name: 'Chinese (Traditional)' },
    { code: 'zu', name: 'Zulu' },
];

export interface ICollabLanguage {
    code: string,
    name: string
}