name: Build TypeScript

on:
  push:
    branches:
      - master  # ou a branch que você deseja monitorar
  pull_request:
    branches:
      - master  # ou a branch que você deseja monitorar

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '14'  # ou a versão do Node.js que você está usando

    - name: Install dependencies
      run: npm install

    - name: Pre Compile TypeScript
      run: npm run prebuild

    - name: Compile TypeScript
      run: npm run buildcmd

    - name: Pos Compile TypeScript
      run: npm run posbuild

    - name: Commit compiled files
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add . ':!node_modules'
        git commit -m "Compile TypeScript files"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Push changes
      run: git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create file Info
      run: npm run createfileinfo

    - name: Commit fileinfo files
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add . ':!node_modules'
        git commit -m "Upp File Info"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Push changes
      run: git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
