name: Delete Branch After PR Closed

on:
  pull_request:
    types:
      - closed

jobs:
  delete_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
      
      - name: Clone the repository
        run: |
          git clone https://github.com/${{ github.repository }} repo
          cd repo
          git checkout master # Certifique-se de estar no branch principal

      - name: Delete branch
        if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd repo
          echo "Branch to delete: ${{ github.event.pull_request.head.ref }}"
          git push origin --delete "${{ github.event.pull_request.head.ref }}"
