name: Delete Branch After PR Closed

on:
  pull_request:
    types:
      - closed

jobs:
  delete_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Delete branch
        if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Branch to delete: ${{ github.event.pull_request.head.ref }}"
          git push origin --delete "${{ github.event.pull_request.head.ref }}"
